create table if not exists public.items (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  content text not null check (char_length(trim(content)) > 0),
  category text not null default 'general',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.items enable row level security;

-- B4-2 학습용 anonymous CRUD 정책입니다.
-- 민감 데이터를 저장하는 실서비스에는 그대로 사용하지 않습니다.
create policy "b4_2_public_select" on public.items for select to anon using (true);
create policy "b4_2_public_insert" on public.items for insert to anon with check (true);
create policy "b4_2_public_update" on public.items for update to anon using (true) with check (true);
create policy "b4_2_public_delete" on public.items for delete to anon using (true);
